import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { HIDDEN_TOOLS, INDEXABLE_TOOLS } from '../src/toolsData.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const distDir = join(__dirname, '../dist');
const DOMAIN = 'https://panutility.vercel.app';

// Read index.html generated by Vite
const template = await readFile(join(distDir, 'index.html'), 'utf8');

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function buildMetaAndHead(options: {
  title: string;
  description: string;
  canonical?: string;
  robots: string;
  keywords: string;
  jsonLdScripts: object[];
}): string {
  const { title, description, canonical, robots, keywords, jsonLdScripts } = options;

  const jsonLdTags = jsonLdScripts
    .map((s) => `<script type="application/ld+json" data-seo="panutility-jsonld">${JSON.stringify(s)}</script>`)
    .join('\n    ');

  return [
    `<title>${escapeHtml(title)}</title>`,
    `<meta name="description" content="${escapeHtml(description)}" />`,
    `<meta name="keywords" content="${escapeHtml(keywords)}" />`,
    `<meta name="author" content="PanUtility" />`,
    `<meta name="robots" content="${escapeHtml(robots)}" />`,
    canonical ? `<link rel="canonical" href="${escapeHtml(canonical)}" />` : '',
    `<meta property="og:site_name" content="PanUtility" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:title" content="${escapeHtml(title)}" />`,
    `<meta property="og:description" content="${escapeHtml(description)}" />`,
    canonical ? `<meta property="og:url" content="${escapeHtml(canonical)}" />` : '',
    `<meta property="og:image" content="${DOMAIN}/og-image.svg" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${escapeHtml(title)}" />`,
    `<meta name="twitter:description" content="${escapeHtml(description)}" />`,
    `<meta name="twitter:image" content="${DOMAIN}/og-image.svg" />`,
    jsonLdTags,
  ].join('\n    ');
}

function injectHeadAndBody(html: string, headHtml: string, bodyHtml: string): string {
  // Replace existing title and head tags
  let result = html;

  // Strip existing title/meta/canonical tags from template head to prevent duplication
  result = result.replace(/<title>.*?<\/title>/s, '');
  result = result.replace(/<meta name="description" content=".*?" \/>/s, '');
  result = result.replace(/<meta name="keywords" content=".*?" \/>/s, '');
  result = result.replace(/<meta name="robots" content=".*?" \/>/s, '');
  result = result.replace(/<link rel="canonical" href=".*?" \/>/s, '');
  result = result.replace(/<meta property="og:.*?" content=".*?" \/>/g, '');
  result = result.replace(/<meta name="twitter:.*?" content=".*?" \/>/g, '');

  // Inject new head elements right before </head>
  result = result.replace('</head>', `    ${headHtml}\n  </head>`);

  // Inject prerendered SSR content into <div id="root"></div>
  result = result.replace('<div id="root"></div>', `<div id="root">${bodyHtml}</div>`);

  return result;
}

// 1. Prerender Homepage
const homepageTitle = 'PanUtility - Universal Media & Format Workstation';
const homepageDesc = 'A transparent all-in-one utility catalog with clear availability and browser, server, or third-party processing labels.';
const homepageCanonical = `${DOMAIN}/`;
const homepageRobots = 'index, follow';
const homepageKeywords = 'utility tools, browser media converter, pdf compiler, audio tools, qr code generator, online utilities';

const webSiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'PanUtility',
  url: `${DOMAIN}/`,
  description: homepageDesc,
};

const orgSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'PanUtility',
  url: `${DOMAIN}/`,
  logo: `${DOMAIN}/favicon.svg`,
};

const homepageHead = buildMetaAndHead({
  title: homepageTitle,
  description: homepageDesc,
  canonical: homepageCanonical,
  robots: homepageRobots,
  keywords: homepageKeywords,
  jsonLdScripts: [webSiteSchema, orgSchema],
});

const homepageToolsGrid = INDEXABLE_TOOLS.map((t) => `
  <a href="/tools/${t.id}" class="tool-card border border-zinc-800 bg-[#111114] rounded-xl p-5 shadow-xl hover:border-emerald-500/30 flex flex-col justify-between gap-4">
    <div>
      <span class="text-[9px] bg-zinc-850 text-zinc-400 border border-zinc-750 px-2 py-0.5 rounded font-mono uppercase tracking-wider">${escapeHtml(t.category)}</span>
      <h3 class="font-sans font-bold text-base text-white tracking-tight mt-2">${escapeHtml(t.name)}</h3>
      <p class="text-zinc-400 text-xs mt-1.5 leading-relaxed">${escapeHtml(t.description)}</p>
    </div>
    <div class="text-[10px] text-emerald-400 font-mono font-bold">Launch Workspace &rarr;</div>
  </a>
`).join('');

const homepageBody = `
<div class="min-h-screen bg-[#07080a] text-zinc-100 font-sans selection:bg-emerald-500/30">
  <header class="border-b border-zinc-800/80 bg-[#0c0c0e]/80 backdrop-blur-md sticky top-0 z-40">
    <div class="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
      <a href="/" class="flex items-center gap-3 group">
        <div class="w-9 h-9 rounded-xl bg-gradient-to-tr from-emerald-600 to-teal-400 p-0.5 shadow-lg shadow-emerald-950/40">
          <div class="w-full h-full bg-[#07080a] rounded-[10px] flex items-center justify-center text-emerald-400 font-bold text-base">⚡</div>
        </div>
        <div>
          <h1 class="font-sans text-lg font-black tracking-tight text-white flex items-center gap-1.5">
            PanUtility <span class="text-[10px] uppercase font-mono tracking-widest bg-emerald-950/60 text-emerald-400 border border-emerald-800/50 px-1.5 py-0.5 rounded font-bold">2026</span>
          </h1>
          <p class="text-[10px] text-zinc-400 font-mono tracking-wide">Universal Media &amp; Format Workstation</p>
        </div>
      </a>
    </div>
  </header>

  <main class="max-w-6xl mx-auto px-4 py-8">
    <section class="mb-10 text-center sm:text-left">
      <h1 class="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">PanUtility Workstation</h1>
      <p class="text-zinc-400 text-sm sm:text-base mt-2 max-w-2xl leading-relaxed">${escapeHtml(homepageDesc)}</p>
    </section>

    <section aria-labelledby="all-tools-heading">
      <h2 id="all-tools-heading" class="text-sm font-bold text-white uppercase tracking-wider font-mono mb-4">Available Indexable Utilities (${INDEXABLE_TOOLS.length})</h2>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        ${homepageToolsGrid}
      </div>
    </section>
  </main>
</div>
`;

const prerenderedHomepageHtml = injectHeadAndBody(template, homepageHead, homepageBody);
await writeFile(join(distDir, 'index.html'), prerenderedHomepageHtml, 'utf8');

// 2. Prerender All Indexable (Public Functional) Tool Pages
let prerenderCount = 0;
for (const tool of INDEXABLE_TOOLS) {
  const canonical = `${DOMAIN}/tools/${tool.id}`;
  const title = `${tool.name} - PanUtility`;
  const processingCopy = tool.processingType === 'browser'
    ? 'Processed locally in your browser.'
    : tool.processingType === 'server'
      ? 'This operation sends data to PanUtility’s server.'
      : tool.processingType === 'external'
        ? 'This operation uses a third-party provider.'
        : 'Processing is currently unavailable.';
  const description = `${tool.description} ${processingCopy}`;
  const keywords = `${tool.name.toLowerCase()}, ${tool.category.toLowerCase()}, in-browser ${tool.name.toLowerCase()}, secure utility tool`;
  const robots = 'index, follow';

  const webAppSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: tool.name,
    url: canonical,
    operatingSystem: 'Web Browser',
    applicationCategory: tool.category || 'UtilityApplication',
    description: tool.description,
    offers: {
      '@type': 'Offer',
      price: '0.00',
      priceCurrency: 'USD',
    },
    browserRequirements: 'Requires HTML5 compatible web browser',
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: `${DOMAIN}/`,
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: tool.category || 'Utilities',
        item: `${DOMAIN}/`,
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: tool.name,
        item: canonical,
      },
    ],
  };

  const toolHead = buildMetaAndHead({
    title,
    description,
    canonical,
    robots,
    keywords,
    jsonLdScripts: [webAppSchema, breadcrumbSchema],
  });

  const sameCategory = INDEXABLE_TOOLS.filter((t) => t.id !== tool.id && t.category === tool.category);
  const otherCategory = INDEXABLE_TOOLS.filter((t) => t.id !== tool.id && t.category !== tool.category);
  const relatedTools = [...sameCategory, ...otherCategory].slice(0, 4);

  const relatedHtml = relatedTools.map((t) => `
    <a href="/tools/${t.id}" class="group bg-[#0d0d0f] border border-zinc-800/80 hover:border-emerald-500/50 p-3 rounded-xl transition-all duration-200 flex flex-col justify-between">
      <div>
        <span class="text-[9px] font-bold text-zinc-500 uppercase tracking-widest block mb-1">${escapeHtml(t.category)}</span>
        <h3 class="text-xs font-semibold text-white group-hover:text-emerald-400 transition-colors line-clamp-1">${escapeHtml(t.name)}</h3>
        <p class="text-[11px] text-zinc-400 mt-1 line-clamp-2 leading-relaxed">${escapeHtml(t.description)}</p>
      </div>
      <div class="mt-3 flex items-center justify-between text-[10px] text-emerald-400 font-mono">
        <span>Open Tool &rarr;</span>
        <span class="text-zinc-500 text-[9px] uppercase">${escapeHtml(t.status)}</span>
      </div>
    </a>
  `).join('');

  const toolBody = `
<div class="min-h-screen bg-[#07080a] text-zinc-100 font-sans selection:bg-emerald-500/30">
  <div data-testid="enabled-tool-workspace">
    <nav aria-label="Breadcrumb" class="mx-auto max-w-4xl px-4 py-2.5 mb-3 flex items-center text-xs text-zinc-400 border-b border-zinc-800/40">
      <ol class="flex items-center gap-1.5 flex-wrap">
        <li><a href="/" class="hover:text-emerald-400 font-medium">Home</a></li>
        <li class="text-zinc-600">/</li>
        <li><span class="text-zinc-400 font-medium">${escapeHtml(tool.category)}</span></li>
        <li class="text-zinc-600">/</li>
        <li><span class="text-emerald-400 font-semibold truncate max-w-[200px]" aria-current="page">${escapeHtml(tool.name)}</span></li>
      </ol>
    </nav>
    <div class="mx-auto max-w-4xl px-4">
      <h1 class="text-3xl font-extrabold text-white tracking-tight mb-2">${escapeHtml(tool.name)}</h1>
      <p class="text-zinc-400 text-sm mb-6 leading-relaxed">${escapeHtml(description)}</p>
    </div>
    <section aria-labelledby="related-tools-heading" class="mx-auto max-w-4xl px-4 mt-10 pt-6 border-t border-zinc-800/60">
      <div class="flex items-center justify-between mb-4">
        <h2 id="related-tools-heading" class="text-sm font-bold text-white uppercase tracking-wider font-mono">Related ${escapeHtml(tool.category)} Utilities</h2>
        <a href="/" class="text-xs text-emerald-400 hover:underline font-medium">View All Utilities &rarr;</a>
      </div>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        ${relatedHtml}
      </div>
    </section>
  </div>
</div>
`;

  const toolHtml = injectHeadAndBody(template, toolHead, toolBody);
  const toolDir = join(distDir, 'tools', tool.id);
  await mkdir(toolDir, { recursive: true });
  await writeFile(join(toolDir, 'index.html'), toolHtml, 'utf8');
  prerenderCount++;
}

// 3. Generate noindex raw HTML for known hidden routes.
// These files are intentionally excluded from sitemap/indexability while
// preventing crawlers from seeing homepage metadata for unavailable tools.
let hiddenCount = 0;
for (const tool of HIDDEN_TOOLS) {
  const canonical = `${DOMAIN}/tools/${tool.id}`;
  const statusLabel = tool.status === 'beta'
    ? 'Beta preview'
    : tool.status === 'coming-soon'
      ? 'Coming soon'
      : 'Temporarily unavailable';
  const description = tool.status === 'disabled'
    ? (tool.statusReason || 'This tool is temporarily unavailable.')
    : tool.status === 'coming-soon'
      ? 'Processing for this tool is not implemented yet. No file is uploaded and no output is created on this page.'
      : 'This beta tool is not part of the public launch catalog yet. It remains noindex while functionality is being verified.';

  const hiddenHead = buildMetaAndHead({
    title: `${tool.name} Unavailable - PanUtility`,
    description,
    canonical,
    robots: 'noindex, nofollow',
    keywords: `${tool.name.toLowerCase()}, unavailable utility, panutility hidden route`,
    jsonLdScripts: [],
  });

  const hiddenBody = `
<div class="min-h-screen bg-[#07080a] text-zinc-100 font-sans selection:bg-emerald-500/30">
  <main class="mx-auto max-w-3xl px-4 py-12" data-testid="unavailable-tool-raw">
    <a href="/" class="text-xs font-bold uppercase tracking-wider text-emerald-400 hover:text-emerald-300">&larr; Back to PanUtility</a>
    <section class="mt-8 rounded-2xl border border-zinc-800 bg-[#0d0d0f] p-6 shadow-2xl">
      <span class="inline-flex rounded-full border border-amber-500/30 bg-amber-500/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-amber-300">${escapeHtml(statusLabel)}</span>
      <h1 class="mt-4 text-3xl font-extrabold tracking-tight text-white">${escapeHtml(tool.name)}</h1>
      <p class="mt-3 text-sm leading-relaxed text-zinc-400">${escapeHtml(description)}</p>
      <p class="mt-5 text-xs leading-relaxed text-zinc-500">This route is intentionally omitted from the sitemap and marked noindex until the tool is launch-ready.</p>
    </section>
  </main>
</div>
`;

  const hiddenHtml = injectHeadAndBody(template, hiddenHead, hiddenBody);
  const toolDir = join(distDir, 'tools', tool.id);
  await mkdir(toolDir, { recursive: true });
  await writeFile(join(toolDir, 'index.html'), hiddenHtml, 'utf8');
  hiddenCount++;
}

// 4. Generate a noindex 404 document for unknown routes.
const notFoundHead = buildMetaAndHead({
  title: 'Page Not Found - PanUtility',
  description: 'The requested PanUtility page could not be found.',
  robots: 'noindex, nofollow',
  keywords: 'panutility not found',
  jsonLdScripts: [],
});
const notFoundBody = `
<div class="min-h-screen bg-[#07080a] text-zinc-100 font-sans selection:bg-emerald-500/30">
  <main class="mx-auto max-w-3xl px-4 py-12" data-testid="not-found-raw">
    <a href="/" class="text-xs font-bold uppercase tracking-wider text-emerald-400 hover:text-emerald-300">&larr; Back to PanUtility</a>
    <section class="mt-8 rounded-2xl border border-zinc-800 bg-[#0d0d0f] p-6 shadow-2xl">
      <span class="inline-flex rounded-full border border-rose-500/30 bg-rose-500/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-rose-300">404</span>
      <h1 class="mt-4 text-3xl font-extrabold tracking-tight text-white">Tool not found</h1>
      <p class="mt-3 text-sm leading-relaxed text-zinc-400">We could not find a PanUtility tool or page at this URL.</p>
    </section>
  </main>
</div>
`;
await writeFile(join(distDir, '404.html'), injectHeadAndBody(template, notFoundHead, notFoundBody), 'utf8');

console.log(`Prerendered Homepage, ${prerenderCount} indexable tool pages, ${hiddenCount} noindex hidden tool pages, and 404.html in dist/!`);
